import numpy as np
rng = np.random.default_rng(42)
AI_features  = np.array(rng.integers(30,60,(10,4)))
print("AI Features")
print(AI_features)
print("mean")
print(AI_features.mean())
standardized = (AI_features - AI_features.mean())/AI_features.std()
print("standardized")
print(standardized)
print("mean")
print(standardized.mean())
print("std")
print(standardized.std())