import numpy as np
import matplotlib.pyplot as plt
rng = np.random.default_rng(42)
image = np.array(rng.integers(0, 255, (10, 10)))
print(image)
plt.imshow(image, cmap="viridis", vmin=0, vmax=255 , interpolation="nearest")
plt.colorbar(label="Intensity")
plt.title("10x10 Grayscale Image")
plt.show()
print("minimum")
print(np.min(image))
print("maximum")
print(np.max(image))
print("mean")
print(np.mean(image))
mask = (image >= np.mean(image))
result = np.where(mask , 0 , 1)
print(result)
plt.imshow(result, cmap="viridis", vmin=0, vmax=1,interpolation="nearest")
plt.colorbar(label="Intensity")
plt.title("10x10 Grayscale Image")
plt.show()